/**
 * Supabase Database Types — Phase 3
 *
 * CANONICAL SOURCE: This file is the generated source of truth for all DB types.
 * It should be regenerated (overwritten) whenever the schema changes using:
 *
 *   pnpm db:types
 *
 * DO NOT edit this file by hand. Manual edits will be overwritten on next generation.
 *
 * Regeneration command (cloud):
 *   supabase gen types typescript --project-id <your-project-id> > src/types/database.ts
 *
 * Regeneration command (local):
 *   supabase gen types typescript --local > src/types/database.ts
 *
 * Phase 3: This file is hand-authored to match the migrations exactly, since the
 * Supabase CLI requires a live/local project to auto-generate. Once the project
 * is provisioned and migrations are applied, run `pnpm db:types` to regenerate.
 * A reconciliation comment is placed in domain.ts pointing here.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          is_approved: boolean;
          is_admin: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          is_approved?: boolean;
          is_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          is_approved?: boolean;
          is_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'profiles_id_fkey';
            columns: ['id'];
            isOneToOne: true;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      books: {
        Row: {
          id: string;
          title: string;
          author: string | null;
          cover_key: string | null;
          file_key: string;
          format: 'epub';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          author?: string | null;
          cover_key?: string | null;
          file_key: string;
          format?: 'epub';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          author?: string | null;
          cover_key?: string | null;
          file_key?: string;
          format?: 'epub';
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      user_libraries: {
        Row: {
          id: string;
          user_id: string;
          book_id: string;
          added_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          book_id: string;
          added_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          book_id?: string;
          added_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'user_libraries_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'user_libraries_book_id_fkey';
            columns: ['book_id'];
            isOneToOne: false;
            referencedRelation: 'books';
            referencedColumns: ['id'];
          },
        ];
      };
      reading_progress: {
        Row: {
          id: string;
          user_id: string;
          book_id: string;
          cfi: string | null;
          percentage: number;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          book_id: string;
          cfi?: string | null;
          percentage?: number;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          book_id?: string;
          cfi?: string | null;
          percentage?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'reading_progress_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'reading_progress_book_id_fkey';
            columns: ['book_id'];
            isOneToOne: false;
            referencedRelation: 'books';
            referencedColumns: ['id'];
          },
        ];
      };
      // Phase 10 (migration 0011): capture-only reading-statistics foundation.
      reading_sessions: {
        Row: {
          id: string;
          user_id: string;
          book_id: string;
          started_at: string;
          ended_at: string;
          duration_seconds: number;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          book_id: string;
          started_at: string;
          ended_at: string;
          duration_seconds: number;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          book_id?: string;
          started_at?: string;
          ended_at?: string;
          duration_seconds?: number;
          created_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'reading_sessions_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'reading_sessions_book_id_fkey';
            columns: ['book_id'];
            isOneToOne: false;
            referencedRelation: 'books';
            referencedColumns: ['id'];
          },
        ];
      };
      // Phase 12 (migration 0012): cloud-synced reader preferences.
      user_preferences: {
        Row: {
          user_id: string;
          preferences: Json;
          version: number;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          preferences?: Json;
          version?: number;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          preferences?: Json;
          version?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'user_preferences_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: true;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      custom_access_token_hook: {
        Args: { event: Json };
        Returns: Json;
      };
    };
    Enums: {
      book_format: 'epub';
    };
    CompositeTypes: Record<string, never>;
  };
};

// ---------------------------------------------------------------------------
// Convenience type aliases (consumed by domain.ts and feature code)
// ---------------------------------------------------------------------------
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];

export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];
